---
name: Net-Whois-Parser
version: 0.02
author:
  - 'Ivan Sokolov <ivsokolov@cpan.org>'
abstract: module for parsing whois information
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Net::Whois::Raw: 2
  Test::More: 0
provides:
  Net::Whois::Parser:
    file: lib/Net/Whois/Parser.pm
    version: 0.02
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
